# Generated by Django 5.1 on 2024-09-10 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('core', '0003_alter_emailverification_email_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('date_to', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ManyToManyField(to='restaurants.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=130)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(blank=True, choices=[('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('restaurant_manager', 'Restaurant Manager'), ('cashier', 'Cashier'), ('assistant_restaurant_manager', 'Assistant Restaurant Manager'), ('host', 'Host'), ('kitchen_porter', 'Kitchen Porter'), ('server', 'Server'), ('dish_washer', 'Dish Washer')], max_length=28, null=True)),
                ('restaurants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='AssistantRestaurantManager',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant Restaurant Manager',
                'verbose_name_plural': 'Assistant Restaurant Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='DishWasher',
            fields=[
            ],
            options={
                'verbose_name': 'Dish Washer',
                'verbose_name_plural': 'Dish Washers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='KitchenPorter',
            fields=[
            ],
            options={
                'verbose_name': 'Kitchen Porter',
                'verbose_name_plural': 'Kitchen Porters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='LineCook',
            fields=[
            ],
            options={
                'verbose_name': 'Line Cook',
                'verbose_name_plural': 'Line Cooks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
            ],
            options={
                'verbose_name': 'Restaurant Manager',
                'verbose_name_plural': 'Restaurant Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='SousChef',
            fields=[
            ],
            options={
                'verbose_name': 'Sous Chef',
                'verbose_name_plural': 'Sous Chefs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
    ]
