# Generated by Django 5.0.8 on 2024-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('restaurant_manager', 'Restaurant Manager'), ('cashier', 'Cashier'), ('assistant_restaurant_manager', 'Assistant Restaurant Manager'), ('host', 'Host'), ('kitchen_porter', 'Kitchen Porter'), ('server', 'Server'), ('dish_washer', 'Dish Washer')], max_length=28, null=True),
        ),
    ]
