# Generated by Django 5.0.6 on 2024-11-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstock',
            name='mode',
            field=models.BooleanField(default=True),
        ),
    ]
