# Generated by Django 5.0.6 on 2024-11-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantstock_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantstock',
            name='stock_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
