# Generated by Django 5.0.6 on 2024-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_staff_restaurants_delete_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantRestaurantManager',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant Restaurant Manager',
                'verbose_name_plural': 'Assistant Restaurant Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='DishWasher',
            fields=[
            ],
            options={
                'verbose_name': 'Dish Washer',
                'verbose_name_plural': 'Dish Washers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='KitchenPorter',
            fields=[
            ],
            options={
                'verbose_name': 'Kitchen Porter',
                'verbose_name_plural': 'Kitchen Porters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='LineCook',
            fields=[
            ],
            options={
                'verbose_name': 'Line Cook',
                'verbose_name_plural': 'Line Cooks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
            ],
            options={
                'verbose_name': 'Restaurant Manager',
                'verbose_name_plural': 'Restaurant Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.CreateModel(
            name='SousChef',
            fields=[
            ],
            options={
                'verbose_name': 'Sous Chef',
                'verbose_name_plural': 'Sous Chefs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurants.staff',),
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('restaurant_manager', 'Restaurant Manager'), ('cashier', 'Cashier'), ('assistant_restaurant_manager', 'Assistant Restaurant Manager'), ('host', 'Host'), ('kitchen_porter', 'Kitchen Porter'), ('server', 'Server'), ('dish_washer', 'Dish Washer')], max_length=28, null=True),
        ),
    ]
