# Generated by Django 5.0.6 on 2024-11-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0002_delete_restaurantstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.URLField(blank=True, null=True)),
                ('stock_type', models.CharField(max_length=128)),
                ('purchasing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('measuring_unit', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocks', to='inventory.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='restaurants.restaurantstore')),
            ],
        ),
    ]
