# Generated by Django 5.0.6 on 2024-12-04 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurantstock_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_menuitem_image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_menuitem_video'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_business_license'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cac_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_cac_certificate'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_cover_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_profile_image'),
        ),
        migrations.AlterField(
            model_name='restaurantstock',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_stock_image'),
        ),
        migrations.AlterField(
            model_name='restaurantstore',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_store_image'),
        ),
    ]
