# Generated by Django 5.0.6 on 2024-11-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailverification_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email_code',
            field=models.CharField(default='901890', max_length=6),
        ),
    ]
