# Generated by Django 5.0.6 on 2024-08-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailverification_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email_code',
            field=models.CharField(default='381b01', max_length=6),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='abc91a', max_length=6),
        ),
    ]
