# Generated by Django 5.0.6 on 2024-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smsverification_sms_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='f9bfe7', max_length=6),
        ),
    ]
