# Generated by Django 5.0.6 on 2024-08-29 23:45

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='ecadda', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
