# Generated by Django 5.0.6 on 2024-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_smsverification_sms_code_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='6ce0a6', max_length=6),
        ),
    ]
