# Generated by Django 5.0.6 on 2024-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_emailverification_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='bvn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email_code',
            field=models.CharField(default='2c8a78', max_length=6),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='b91a91', max_length=6),
        ),
    ]
