# Generated by Django 5.0.6 on 2024-08-21 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_account_account_number_alter_account_bvn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email_code',
            field=models.CharField(default='5e133a', max_length=6),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='311d56', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Username.', message="Username must be Alpha-Numeric and may also contain '.', '@' and '_'.", regex='^[a-zA-Z0-9.@_]*$')], verbose_name='username'),
        ),
    ]
