# Generated by Django 5.0.6 on 2024-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emailverification_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email_code',
            field=models.CharField(default='00c2e8', max_length=6),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='sms_code',
            field=models.CharField(default='63380a', max_length=6),
        ),
    ]
