# Generated by Django 5.0.6 on 2024-10-06 04:26

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('unit_of_measure', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A restaurant with that phone number already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('cac_reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cac_certificate', models.FileField(upload_to='images/supplier/cac_certificates')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='images/supplier/business_license')),
                ('category', models.CharField(choices=[('sea_food', 'Sea Food'), ('vegetables', 'Vegetables'), ('meat_and_poultry', 'Meat and Poultry'), ('grains', 'Grain Products'), ('soup_and_condiments', 'Soups and Condiments'), ('spices_and_seasoning', 'Spices and Seasoning'), ('oil_and_fat', 'Oil and Fat'), ('baking_products', 'Baking Products'), ('fruits_and_nuts', 'Fruits and Nuts'), ('diary_products', 'Diary Products'), ('spread_and_sweeteners', 'Spread and Sweeteners'), ('drinks_and_beverages', 'Drinks and Beverages')], max_length=21)),
                ('profile_img', models.ImageField(upload_to='images/restaurant/profile_images')),
                ('cover_img', models.ImageField(upload_to='images/restaurant/cover_images')),
                ('address', models.CharField(max_length=130)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ManyToManyField(to='cities_light.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='SupplyManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('supply_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            bases=('core.user',),
        ),
    ]
