# Generated by Django 5.0.6 on 2024-10-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='supplymanager',
            name='account_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplymanagers', to='banking.accountdetail'),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.ManyToManyField(related_name='suppliers', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant/cover_images'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant/profile_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ManyToManyField(related_name='suppliers', to='inventory.category'),
        ),
    ]
