# Generated by Django 5.0.6 on 2024-12-04 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='inventory_stocks'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='supplier_business_license'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cac_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='supplier_cac_certificates'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='supplier_cover_image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='supplier_profile_image'),
        ),
    ]
