# Generated by Django 5.1.3 on 2024-11-12 04:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_supplier_remove_stock_item_item_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplymanager',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A supplier with that phone number already exists.'}, max_length=128, null=True, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
