# Generated by Django 5.1.1 on 2024-10-26 11:16

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '__first__'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('terms_and_condition', models.BooleanField()),
                ('face_capture', models.URLField(blank=True, null=True)),
                ('work_shift', models.JSONField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motoroycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck')], max_length=10, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=256, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('drivers_license', models.URLField(blank=True, null=True)),
                ('drivers_license_id', models.CharField(blank=True, max_length=20, null=True)),
                ('voters_card', models.URLField(blank=True, null=True)),
                ('voters_number', models.CharField(blank=True, max_length=12, null=True)),
                ('nin_doc', models.URLField(blank=True, null=True)),
                ('nin_number', models.CharField(blank=True, max_length=11, null=True)),
                ('N_O_N_full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('N_O_N_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="next-of-kin's phone number")),
                ('guarantor_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('guarantor_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('guarantor_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="Guarantor's phone number")),
                ('guarantor_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('account_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveryagents', to='banking.accountdetail')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('completed', 'Completed')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deliveryagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.order')),
            ],
            options={
                'db_table': 'deliveryrequest',
            },
        ),
    ]
