# Generated by Django 5.0.6 on 2024-12-04 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='drivers_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_agent_drivers_license'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='face_capture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_agent_face_capture'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='nin_doc',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_agent_nin_doc'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='voters_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='delivery_agent_voters_card'),
        ),
    ]
