# Generated by Django 5.0.6 on 2024-10-19 04:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='account_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveryagents', to='banking.accountdetail'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='terms_and_condition',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='work_shift',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='N_O_N_full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='N_O_N_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="next-of-kin's phone number"),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='address',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='face_capture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='guarantor_first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='guarantor_last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='guarantor_occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='guarantor_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="Guarantor's phone number"),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motoroycle'), ('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck')], max_length=10, null=True),
        ),
    ]
