# Generated by Django 5.1.3 on 2024-11-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, upload_to='images/drivers_license'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='face_capture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='nin_doc',
            field=models.FileField(blank=True, null=True, upload_to='images/NIN_doc'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='voters_card',
            field=models.FileField(blank=True, null=True, upload_to='images/voters_card'),
        ),
    ]
